name: Send Slack Msg

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    pr_send_slack_msg:
        name: send slack message for PR
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: send PR to slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.19.0
              with:
                  payload: |
                      {
                        "event_name": "${{ github.event_name }}",
                        "event_html_url": "${{ github.event.pull_request.html_url }}",
                        "repo_name": "${{ github.event.repository.name }}"
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SEND_MSG}}

    issue_send_slack_msg:
        name: send slack message for issue
        if: github.event_name == 'issues'
        runs-on: ubuntu-latest
        steps:
            - name: send issue to slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.19.0
              with:
                  payload: |
                      {
                        "event_name": "${{ github.event_name }}",
                        "event_html_url": "${{ github.event.issue.html_url }}",
                        "repo_name": "${{ github.event.repository.name }}"
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SEND_MSG }}
